services:
  redis:
    image: redis:7
    container_name: redis
    ports:
      - "6379:6379"
    restart: always

  server:
    build: ./server
    ports:
      - "3000:3000"
    env_file:
      - ./server/.env
    depends_on:
      - redis
      - recommender
      - sentiment
      - elasticsearch

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.11.1
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ports:
      - "9200:9200"
    restart: always

  client:
    build: ./client
    ports:
      - "5173:5173"
    depends_on:
      - server

  recommender:
    build: ./recommender
    ports:
      - "8002:8002"

  sentiment:
    build: ./sentiment-service
    ports:
      - "8001:8001"
